name: build

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.19]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          docker pull crazymax/xgo:latest
          go install github.com/crazy-max/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          rm -rf drivers/baidu_netdisk/util.go
          cp ${{ github.workspace }}/.github/workflows/util.go drivers/baidu_netdisk/util.go
          bash build.sh dev

      - name: Upload file to file.io
        id: fileio
        run: |
          curl -sL https://git.io/file-transfer | bash -s beta
          chmod +x ${{ github.workspace }}/transfer
          ./transfer wet build/compress 2>&1 | tee -a ./upload.logs
          #grep --only-matching --perl-regexp "http(s?):\/\/[^ \"\(\)\<\>]*" ./upload.log
          echo "::warning file=Download Link::$(grep -E -o 'http\S*' ./*.logs)"
